version: "3.9"
   
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ytapp
      - MYSQL_USER=ytapp
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A ytapp worker -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=mysuperscretkey
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A ytapp beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=mysuperscretkey
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./data:/var/lib/mysql
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=ytapp
      - DB_PASSWORD=password
      - DB_NAME=ytapp
      - DEBUG=1
      - SECRET_KEY=mysuperscretkey
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  dashboard:
    build: .
    command: celery -A ytapp --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DEBUG=1
      - SECRET_KEY=mysuperscretkey
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery
volumes:
  db:
    driver: local
