# Generated by Django 4.0.6 on 2022-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytvideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideostat',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
