# Generated by Django 4.0.6 on 2022-08-01 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ytvideo', '0002_ytvideostat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideostat',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
